services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1231
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "demo", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    container_name: db
  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DEV_PASSWORD=1231
      - DEV_USERNAME=postgres
      - DEV_DB_URL_DOCKER=jdbc:postgresql://db:5432/demo

